title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: true
theme: jekyll-theme-cayman

conference_name: "Tutorial on Large Language Models for Recommendation: Progresses and Future Direction"
# conference_www: "on the Web Conference 2024 (WWW'24)"
conference_www: "Collection of Tutorials on Large Language Models for Recommendation"
# conference_venue: "Singapore, Monday 13 - Friday 17 May 2024"
conference_venue: ""
# conference_intro: "Will be held in 2024"
conference_intro: ""

github:
  workshop_url: https://generative-rec.github.io/
  survey_url: https://generative-rec.github.io/survey/

collections:
  organizers:
    output: true
  speakers:
    output: true
